language: node_js
node_js:
- node
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: enriquegh.com
  acl: public_read
  region: us-west-2
  on:
    repo: enriquegh/enriquegh_website
